default: &default
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000
