default: &default
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: budgetdb
  username: postgres
  password: new
  host: localhost
  pool: 5
  timeout: 5000
  port: 5432
